# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Takepoyo"
description: > # this means to ignore newlines until "email:"
   Computer engineering student in Kyoto

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/icon2.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/light-gray.png"

name: 'Dirk Fabisch'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@***********'

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/********
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/onagonanja
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
